/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as flpCrowndsaleSol from "./FLPCrowndsale.sol";
export type { flpCrowndsaleSol };
import type * as heroSol from "./Hero.sol";
export type { heroSol };
export type { Auction } from "./Auction";
export type { Floppy } from "./Floppy";
export type { HeroMarketplace } from "./HeroMarketplace";
export type { USDT } from "./USDT";
export type { Vault } from "./Vault";
