/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type { IHero, IHeroInterface } from "../../../contracts/Hero.sol/IHero";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "hero_type",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IHero__factory {
  static readonly abi = _abi;
  static createInterface(): IHeroInterface {
    return new utils.Interface(_abi) as IHeroInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IHero {
    return new Contract(address, _abi, signerOrProvider) as IHero;
  }
}
